---
name: Test ntpdate

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 'latest'

      - name: Install dependencies
        run: |
          cpanm -iqn Net::NTPTime DateTime Sys::Syslog Config::Simple B::Lint warnings::unused IPC::System::Simple
          cpanm -iqn warnings::unused

      - name: Run script with test NTP server
        run: |
          perl ./ntpdate pool.ntp.org || echo "Script execution failed"

      - name: Lint Perl script
        run: |
          perl -MO=Lint ./ntpdate
          perl -c -Mwarnings::unused ./ntpdate
