---
name: Test ntpdate

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 'latest'

      - name: Install dependencies
        run: |
          # cpanm Net::NTPTime DateTime Sys::Syslog Config::Simple B::Lint
          cpanm Net::NTPTime DateTime Sys::Syslog Config::Simple

      - name: Run script with test NTP server
        run: |
          perl ./ntpdate pool.ntp.org || echo "Script execution failed"

      - name: Lint Perl script
        run: |
          # perl -MO=Lint ./ntpdate
          perl -c -Mwarnings::unused ./ntpdate
